################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Hardware/TOUCH/ctiic.c \
../Hardware/TOUCH/ft5206.c \
../Hardware/TOUCH/gt9147.c \
../Hardware/TOUCH/gt9271.c \
../Hardware/TOUCH/ott2001a.c \
../Hardware/TOUCH/touch.c 

OBJS += \
./Hardware/TOUCH/ctiic.o \
./Hardware/TOUCH/ft5206.o \
./Hardware/TOUCH/gt9147.o \
./Hardware/TOUCH/gt9271.o \
./Hardware/TOUCH/ott2001a.o \
./Hardware/TOUCH/touch.o 

C_DEPS += \
./Hardware/TOUCH/ctiic.d \
./Hardware/TOUCH/ft5206.d \
./Hardware/TOUCH/gt9147.d \
./Hardware/TOUCH/gt9271.d \
./Hardware/TOUCH/ott2001a.d \
./Hardware/TOUCH/touch.d 


# Each subdirectory must supply rules for building sources it contributes
Hardware/TOUCH/ctiic.o: ../Hardware/TOUCH/ctiic.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/ctiic.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Hardware/TOUCH/ft5206.o: ../Hardware/TOUCH/ft5206.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/ft5206.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Hardware/TOUCH/gt9147.o: ../Hardware/TOUCH/gt9147.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/gt9147.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Hardware/TOUCH/gt9271.o: ../Hardware/TOUCH/gt9271.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/gt9271.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Hardware/TOUCH/ott2001a.o: ../Hardware/TOUCH/ott2001a.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/ott2001a.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Hardware/TOUCH/touch.o: ../Hardware/TOUCH/touch.c Hardware/TOUCH/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/sys" -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/USMART" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/LCD" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/SYSTEM/delay" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Task" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/KEY" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/IIC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/24CXX" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/AP3216C" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/PCF8574" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/TOUCH" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/SDRAM" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/ADC" -I"/Users/apeelab1/Documents/STMCUBEPROJECT/test624/test624/Hardware/DAC" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Hardware/TOUCH/touch.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

